### ISSUE TITLE
Exception: API Error

### ISSUE THREAD

**Issue by bofeng** [Tesorio/spamcheck-python#2]
I tried the example code in README, gave me this error:

`
Exception: API Error
`

I check the response status code is 500.

Then I changed the line from 

`response = requests.post(API_URL, data, headers=headers)
`
to 

```
import json
response = requests.post(API_URL, json.dumps(data), headers=headers)
```

And now it works. So I think you may want to add `json.dumps` when send post request 😄

**Comment by FabioFleitas** [comment]
Hi @bofeng - thanks for bringing this issue to our attention. I went ahead and fixed it and deployed a new version `1.0.2` to PyPI so you should be able to update it with `pip install --upgrade spamcheck`
