### ISSUE TITLE
Server Failure

### ISSUE THREAD

**Issue by uayyappa** [Tesorio/spamcheck-python#6]
Hi,
Good day we are facing lot's of issues due to use for spam checker package 
 in link given .(https://pypi.python.org/pypi/spamcheck).we noticed that failure is occurring regularly.

**Comment by FabioFleitas** [comment]
Hi @uayyappa seems like the [Spamcheck API](https://spamcheck.postmarkapp.com) hosted by Postmark is currently down. This is, unfortunately, out of our control as we only provide a Python wrapper.
