### ISSUE TITLE
AttributeError: module 'spamcheck' has no attribute 'check'

### ISSUE THREAD

**Issue by badijm** [Tesorio/spamcheck-python#7]
Hello. 
I try to run your module for my university reaserach my I got this error?

`AttributeError: module 'spamcheck' has no attribute 'check'`

I tried both 2.7 and 3.6 Py versions.

**Comment by FabioFleitas** [comment]
Hi @badijm - do you happen to have another module in your code called `spamcheck`?

**Comment by FabioFleitas** [comment]
Going to go ahead and close this issue, but feel free to open it if you continue to have issues.

**Comment by badijm** [comment]
@FabioFleitas Only one pip package was installed.

**Comment by badijm** [comment]
@FabioFleitas Problem solved! thanks
